### PR TITLE
Changes I made

### PR DESCRIPTION
**Pull request by Wenykeny**
I made a couple of changes on these files

### CODE REVIEW

**Comment by ZenitH-AT** [comment]
I've also made changes to these files earlier, so I will manually go through the changes and see.

I think that the fields for student should stay required.

**Comment by ZenitH-AT** [comment]
Another issue is the select box's default value will not reflect the current one. I will need to have an if statement to change the ordering.

**Comment by ZenitH-AT** [comment]
I found a few errors in the admins thing so I slightly adjusted it.

**Comment by ZenitH-AT** [comment]
You needed to use this 
```php
isActive  = '{$_POST['isActive' . $row['studID']]}'
```
Not this
```php
isActive  = '{$_POST['isActive' . $row['isActive']]}'
```
I changed it in the select in the form as well.

**Comment by ZenitH-AT** [comment]
I've merged all your changes

**Comment by Wenykeny** [comment]
I’ve tested those things but anyways I’m gonna download later on to check if everything is working fine on my side and I think tomorrow I’ll go through the whole system using Zenaide’s pc just to ensure

**Comment by Wenykeny** [comment]
I’ve tested everything but anyways.
I’ll download the system later to check if everything is working jus fine.
 And also, tomorrow I’ll go through the whole system using Zenaide’s PC to ensure that everything single feature is working perfectly.

Cheers Man

**Comment by ZenitH-AT** [comment]
Cool, yeah the only issue is that some of the javascript alerts dont show because I changed header("refresh:0") to a redirect so that the browser stops asking the user to resubmit data when they refresh the page.

But the javascript alert doesnt show then, so I need to make it redirect using js as well. Ill fix it later today

**Comment by Wenykeny** [comment]
Yeah, I’ve try to do that. I did want to expend time restructuring the code. But, if u do so, please make sure everything is done by tomorrow before 10. So that I can download the folder and test every single feature on the website with Zenaide’s Pc for the final presentation.

Cheers Man!!

**Pull request closed without merging**
